<?php
/**
 * Migration 059 — Fix PostgreSQL Identity
 * =====================================
 * Asegura que la columna 'id' de 'sesion_lineas' sea auto-incremental (Identity)
 * en PostgreSQL, resolviendo el error de "null value violates not-null constraint".
 */

use Illuminate\Database\Capsule\Manager as Capsule;

return [
    'up' => function () {
        if (Capsule::connection()->getDriverName() === 'pgsql') {
            // Intentar convertir la columna id en IDENTITY si no lo es
            try {
                Capsule::connection()->unprepared("
                    DO $$ 
                    BEGIN 
                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'sesion_lineas' 
                            AND column_name = 'id' 
                            AND is_identity = 'YES'
                        ) THEN
                            -- Borrar cualquier default previo (como serial) y poner IDENTITY
                            ALTER TABLE sesion_lineas ALTER COLUMN id DROP DEFAULT;
                            ALTER TABLE sesion_lineas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
                            -- Reiniciar secuencia al valor máximo actual
                            PERFORM setval(pg_get_serial_sequence('sesion_lineas', 'id'), coalesce(max(id), 1)) FROM sesion_lineas;
                        END IF;
                    END $$;
                ");
            } catch (\Exception $e) {
                // Si ya existe o hay error, logueamos pero no detenemos el proceso
                error_log("Aviso Migración 059: " . $e->getMessage());
            }
        }
    },
    'down' => function () {
        // No revertimos este cambio estructural de seguridad
    }
];
